server:
  port: 8001
spring:
  application:
    name: eureka
  security:
    user:
      name: itzhiya
      password: itzhiya
eureka:
  dashboard:
    enabled: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://itzhiya:itzhiya@localhost:8005/eureka
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 2000
    peer-node-read-timeout-ms: 5000
logging:
  level:
    com:
      netflix: warn
